---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: retailer-db
  name: retailer-db
  namespace: default
spec:
  ports:
    - name: server-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  loadBalancerSourceRanges:
    - 209.118.184.61/32
    - 209.118.184.62/32
    - 52.9.20.60/32
  selector:
    app: retailer-db
  sessionAffinity: None
  type: LoadBalancer
