---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: retailer-db
  name: retailer-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retailer-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: retailer-db
      name: retailer-db
    spec:
      containers:
        - name: retailer-db
          imagePullPolicy: Always
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: retailer-app-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retailer-app-secrets
                  key: postgres-password
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
